/*
Amar Gupta
Sudipto Bose
Cedric Li-Chay-Chung
*/

drop view SALE_INFO;
drop view STORE_REVENUE;
drop view SHIPMENTS;
drop view SALES;

/* 1. Shows history of all sales with total cost, date, and type for each */

CREATE VIEW SALES AS
SELECT SALE_DATE, QUANTITY * UNIT_PRICE AS TOTAL_REVENUE, SALE_TYPE
FROM PRODUCT_IN_SALE, PRODUCT, SALE
WHERE PRODUCT_IN_SALE.SALEID = SALE.SALEID AND PRODUCT_IN_SALE.PRODUCTID = PRODUCT.PRODUCTID
ORDER BY SALE_TYPE, SALE_DATE;

/* 2. Shows all shipments with total revenue, date, and FULFILLED status for each */

CREATE VIEW SHIPMENTS AS
SELECT SHIPMENT_DATE, QUANTITY * UNIT_PRICE AS TOTAL_COST, FULFILLED
FROM SHIPMENT
ORDER BY FULFILLED, SHIPMENT_DATE;

/* 3. Show total sales revenue per store */

CREATE VIEW STORE_REVENUE AS
SELECT STORE.STOREID, CITY, SUM(PRODUCT_IN_SALE.QUANTITY * PRODUCT_IN_SALE.UNIT_PRICE) as TOTAL_REVENUE
FROM SALE, PRODUCT_IN_SALE, DEPARTMENT, STORE, CASHIER
WHERE DEPARTMENT.STOREID = STORE.STOREID AND DEPARTMENT.DEPARTMENTID = CASHIER.DEPARTMENTID AND SALE.SALE_TYPE = 'SALE' AND
SALE.EMPLOYEEID = CASHIER.EMPLOYEEID AND PRODUCT_IN_SALE.SALEID = SALE.SALEID
GROUP BY STORE.STOREID, CITY
ORDER BY TOTAL_REVENUE DESC;

/* 4. Show sale and corresponding product, supplier, and customer information for all sales */

CREATE VIEW SALE_INFO AS
SELECT SALE.SALEID, CUSTOMER_NAME, EMPLOYEE_NAME, SALE_DATE,
CONCAT(PRODUCT_BRAND, PRODUCT_TYPE) AS PRODUCT,
QUANTITY * UNIT_PRICE AS TOTAL_REVENUE, SALE_TYPE
FROM PRODUCT_IN_SALE PS, PRODUCT, SALE, CUSTOMER, CASHIER, EMPLOYEE
WHERE PS.SALEID = SALE.SALEID AND PS.PRODUCTID = PRODUCT.PRODUCTID AND
SALE.CUSTOMERID = CUSTOMER.CUSTOMERID AND SALE.EMPLOYEEID = CASHIER.EMPLOYEEID AND EMPLOYEE.EMPLOYEEID = SALE.EMPLOYEEID
ORDER BY SALE.SALEID;



/* Display Views */
SELECT * FROM SALES;
SELECT * FROM SHIPMENTS;
SELECT * FROM STORE_REVENUE;
SELECT * FROM SALE_INFO;
