#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "USERNAME/PASSWORD@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.cs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF
SELECT * FROM STORE;
SELECT * FROM SUPPLIER;
SELECT * FROM CUSTOMER;
SELECT * FROM EMPLOYEE;
SELECT * FROM MANAGER;
SELECT * FROM DEPARTMENT;
SELECT * FROM PRODUCT;
SELECT * FROM CASHIER;
SELECT * FROM SALE;
SELECT * FROM SHIPMENT;
SELECT * FROM PRODUCT_IN_SALE;
exit;
EOF
